{
  "name": "smkrest",
  "version": "1.0.0",
  "description": "first attempt",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "^1.13.1",
    "connect-mongo": "^0.8.2",
    "cookie-parser": "^1.3.5",
    "cors": "^2.7.1",
    "express": "^4.13.0",
    "express-session": "^1.11.3",
    "gulp": "^3.9.0",
    "gulp-mocha": "^2.1.2",
    "gulp-nodemon": "^2.0.3",
    "mkdir": "0.0.2",
    "mkdirs": "0.0.2",
    "mongoose": "^4.0.6",
    "negotiator": "^0.5.3",
    "passport": "^0.2.2",
    "passport-local": "^1.0.0",
    "passport-local-mongoose": "^1.0.1",
    "q": "^1.4.1",
    "should": "^7.0.1",
    "sinon": "^1.15.4",
    "winston": "^1.0.1"
  },
  "devDependencies": {
    "chai": "^1.10.0",
    "grunt": "^0.4.5",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-copy": "^0.7.0",
    "grunt-contrib-cssmin": "^0.10.0",
    "grunt-contrib-uglify": "^0.6.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-jade-usemin": "^0.11.0",
    "grunt-karma": "^0.9.0",
    "grunt-mocha-istanbul": "^2.2.0",
    "grunt-usemin": "^2.6.2",
    "istanbul": "^0.3.5",
    "karma": "^0.12.25",
    "karma-chrome-launcher": "^0.1.5",
    "karma-coverage": "^0.2.6",
    "karma-firefox-launcher": "^0.1.3",
    "karma-mocha": "^0.1.9",
    "karma-phantomjs-launcher": "*",
    "karma-sinon-chai": "^0.2.0",
    "mocha": "^2.0.1",
    "sinon": "^1.12.1",
    "supertest": "^0.15.0"
  }
}
